name: GitHub Actions Demo
on: [push]
jobs:
    Test-For-File:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v2
        - name: Check file existance
          id: check_files
          uses: andstor/file-existence-action@v1
          with:
            files: "README.md"
        - name: Has File?
          if: steps.check_files.outputs.files_exists == 'true'
          run: echo No File!
        - name: Has File?
          if: steps.check_files.outputs.files_exists != 'true'
          run: echo We have file!
